### ISSUE TITLE
Undefined symbol (errors when building)

### ISSUE THREAD

**Issue by dddd-zdf** [kewlbear/YoutubeDL#1]
I apologize in advance if I asked any stupid questions or offended anyone since this is my first time using Xcode.
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/5017696/101313710-ba2f2f80-3891-11eb-92ab-d32701049d1c.png">

**Comment by kewlbear** [comment]
What's the version number of the Xcode you are using?

**Comment by bAnonym** [comment]
> What's the version number of the Xcode you are using?

it's 12.2 (12B45b) running on M1 macBook air.

**Comment by kewlbear** [comment]
Oh, I haven't tested it on M1 yet.  I'm waiting for my M1 Mac mini.  If you can wait until 23/12, I'll let you know.  If you find a solution before me, please file a pull request.

**Comment by bAnonym** [comment]
> Oh, I haven't tested it on M1 yet. I'm waiting for my M1 Mac mini. If you can wait until 23/12, I'll let you know. If you find a solution before me, please file a pull request.

sure thing. Thanks for your help!

**Comment by kewlbear** [comment]
After days of trial and error since delivery of my Apple Silicon Mac mini, I finally updated my packages with M1 versions of precompiled libraries.  You should update Swift packages to latest versions and clean build folder first.  After that I was able to run this app on M1 with iOS simulator.  HTH

**Comment by dddd-zdf** [comment]
> After days of trial and error since delivery of my Apple Silicon Mac mini, I finally updated my packages with M1 versions of precompiled libraries. You should update Swift packages to latest versions and clean build folder first. After that I was able to run this app on M1 with iOS simulator. HTH

 I didn't look into it since I've been busy with my final week. Thank you!
