### ISSUE TITLE
ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location

### ISSUE THREAD

**Issue by litt1e-p** [kewlbear/YoutubeDL#12]
I want to use it to extract mp3 only like below code:
```swift
let argv = ["-x", "--audio-format", "mp3", "--embed-thumbnail", "--add-metadata"]
try await yt_dlp(argv: argv)
```
but an error occured: `ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location`. I don't know the right way using `FFmpeg-iOS` and make it works. thanks for some help.

**Comment by kewlbear** [comment]
ffmpeg is embedded into you app but ffprobe is not.  Currently ffprobe is
not built with FFmpeg-iOS package.  You can try building ffprobe yourself,
or wait for me or anyone else to build it if ever.

2023년 3월 30일 (목) 오전 12:06, litt1e-p ***@***.***>님이 작성:

**Comment by litt1e-p** [comment]
but how can `ffmpeg/ffprobe location path` pass to python lib function after them embeded?

**Comment by kewlbear** [comment]
Oh, I see.  I've implemented intercepting Popen method calls and calling embedded ffmpeg.  But I forgot to push it to GitHub.  Will push it soon.

**Comment by kewlbear** [comment]
Pushed it!  Here I call ffmpeg embedded as a function:

https://github.com/kewlbear/YoutubeDL-iOS/blob/c9f755e5a164f1c33b8b2573b789fdb070ec5b3d/Sources/YoutubeDL/YoutubeDL.swift#L433

**Comment by litt1e-p** [comment]
great, but how to use it, may i ask for an example code?

**Comment by kewlbear** [comment]
Your original code should work. But as I said ffprobe is not there. So if the operation requires ffprobe it will probably fail.

**Comment by litt1e-p** [comment]
you're right, it does show `ffprobe` error only now:
```swift
yt_dlp.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe
startDownload(url:) Error Domain=App Code=1 "ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe" UserInfo={NSLocalizedDescription=ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe}
```

**Comment by kewlbear** [comment]
I've added support for ffprobe and mp3lame.  You should be able to do it by upgrading YoutubeDL-iOS package dependency.

**Comment by litt1e-p** [comment]
that is great!I will try it later. Thanks again!

**Comment by litt1e-p** [comment]
@kewlbear it works ! thanks a lot, you are the best
