### ISSUE TITLE
You have requested downloading the video partially, but ffmpeg is not installed

### ISSUE THREAD

**Issue by kientux** [kewlbear/YoutubeDL#19]
I'm facing this error when using example app:

`You have requested downloading the video partially, but ffmpeg is not installed. Aborting`

This is because of this line in python ffmpeg handler:

`raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), args[0])`

<img width="768" alt="image" src="https://github.com/kewlbear/YoutubeDL/assets/4200743/c9c0d613-87af-478d-9595-72168bd6e68b">

When I remove the line, it run through `communicate` function but after all it throws AttributionError:

```
Popen.__init__: <yt_dlp.utils.Popen object at 0x126d28160> (['ffmpeg', '-bsfs'],)
Popen.communicate: <yt_dlp.utils.Popen object at 0x126d28160> () {'timeout': None}
Popen.kill: <yt_dlp.utils.Popen object at 0x126d28160>
Popen.wait: <yt_dlp.utils.Popen object at 0x126d28160> {'timeout': None}
ERROR: 'Popen' object has no attribute '_Pop__args'
```

Please explain the python handler code, I have very little knowledge about python @kewlbear, thanks!

**Comment by kewlbear** [comment]
@kientux Thanks for reporting!  Fixed it.  Please update YoutubeDL-iOS package.
